name: CD

on:
  push:
    branches:
      - master
env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/spring-api

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Spin postgres container
        run: docker-compose -f docker-compose-db.yml up -d

      - name: Check running container
        run: docker-compose -f docker-compose-db.yml ps

      - name: Check logs
        run: docker logs postgres

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: compile
        run: mvn compile

      - name: test
        run: mvn test

      - name: build
        run: mvn package

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${ IMAGE }:${{ github.sha }}

  trigger-deploy:
    name: Dispatch deployement
    runs-on: ubuntu-latest
    needs: [test-and-deploy]
    steps:
      - name: Trigger deployment.
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Trigger deployment
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          inputs: '{ "sha": "${{ github.sha }}" }'
