name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    name: Running Java compile and test.
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Compile code
        run: mvn compile
      - name: Run unit tests
        run: mvn test
