name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: openjdk:11.0.11-jre-slim
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: root123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Compile code
        run: mvn compile
      - name: Run unit tests
        run: mvn test
