name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Running compile and test.
    steps:
      - uses: actions/checkout@v2

      - name: Spin postgres container
        run: docker-compose -f docker-compose-db.yml up -d

      - name: Check running container
        run: docker-compose -f docker-compose-db.yml ps

      - name: Check logs
        run: docker logs postgres

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: compile
        run: mvn compile

      - name: test
        run: mvn test

      - name: build
        run: mvn package
